version: '3.9'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - '8080:80'
    networks:
      - internal
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - internal

networks:
  internal:
